name: SkyClashsPE
main: PocketMiner\SkyClashs\SkyClashs
author: PocketMiner
version: 0.0.1 Miner
api: [1.0.0, 2.0.0]

commands:
    sw:
        usage: /sc <crea>
        description: SkyClashs-Commands
    swlang:
        usage: /lang <en>
        description: SkyClashs-English-Lang
    swstart:
        usage: /scstarta
        description: SkyClashs-Force start
