name: SkyClashsPE
main: PocketMiner\SkyWars\SkyClashsPE
author: PocketMiner
version: 0.0.1
api: [1.0.0, 2.0.0, 3.0.0-ALPHA6, 3.0.1]

commands:
    sw:
        usage: /sc <crea>
        description: SkyClashs-Commands
    swlang:
        usage: /lang <en>
        description: SkyClashs-English-Lang
    swstart:
        usage: /scstarta
        description: SkyClashs-Force start
