name: SkyClashsPE
main: PocketMiner\SkyWars\SkyClashsPE
author: PocketMiner
version: 0.0.1
api: [1.0.0, 2.0.0, 3.0.0-ALPHA6, 3.0.1]

commands:
    sc:
        usage: /sc <crea>
        description: SkyClashs-Commands
    sclang:
        usage: /sclang <en>
        description: SkyClashs-English-Lang
    scstart:
        usage: /scstarta
        description: SkyClashs-Force start
